inject base via script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,6 +30,19 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Conditionally set base in vite.config.ts
+        run: |
+          REPO_NAME="${{ github.event.repository.name }}"
+          CONFIG_FILE='vite.config.ts'
+          BASE_PATTERN="base: '/$REPO_NAME/',"
+
+          if ! grep -q "base:" "$CONFIG_FILE"; then
+            echo "Base property not found. Setting it to '$BASE_PATTERN'"
+            # Use sed to insert the base property directly under the export default defineConfig({
+            sed -i "/export default defineConfig({/a \ \ $BASE_PATTERN" $CONFIG_FILE
+          else
+            echo "Base property already set in $CONFIG_FILE"
+          fi
       - name: Set up Node
         uses: actions/setup-node@v4
         with:
